# https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml
version: 1

host:
  id: "yunohost"

devices:

log:
  file: '/var/log/__APP__/collector.log'
  level: INFO

api:
  endpoint: 'http://127.0.0.1:__PORT____PATH__/'
