# https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml
version: 1

web:
  listen:
    port: __PORT__
    host: 127.0.0.1
    basepath: '__BASE_PATH__'
  database:
    location: '__DATA_DIR__/scrutiny.db'
  src:
    frontend:
      path: '__INSTALL_DIR__/web'
  influxdb:
    #scheme: 'http'
    host: 127.0.0.1
    port: __INFLUXDB_PORT__
    token: '__INFLUXDB_ADMIN_TOKEN__'
    org: '__INFLUXDB_ORG_NAME__'
    bucket: '__INFLUXDB_BUCKET_NAME__'
    retention_policy: true
    # tls:
    #   insecure_skip_verify: false

log:
  file: '/var/log/__APP__/web-server.log'
  level: INFO
