packaging_format = 2

id = "scrutiny"
name = "Scrutiny"
description.en = "WebUI for smartd S.M.A.R.T monitoring"

version = "0.9.3~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "MIT"
admindoc = "https://github.com/AnalogJ/scrutiny/tree/master/docs"
code = "https://github.com/AnalogJ/scrutiny"
fund = "https://paypal.me/analogj/usd10"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.path]
	type = "path"
	default = "/scrutiny"

	[install.collector]
	ask.en = "Should the collector be activated on this host?"
	help.en = "Let it to true if yunohost is running on bare metal (i.e. not in a VM or in a LXC)"
	type = "boolean"
	default = true

[resources]
	[resources.sources]

		[resources.sources.main]
		in_subdir = false
		rename = "scrutiny-web-linux"
		amd64.url = "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.3/scrutiny-web-linux-amd64"
		amd64.sha256 = "4523ac7558224b0e2e73406ba690b1a1c984c1e6c4fa8e8a35cb02b2d8bd5148"
		arm64.url = "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.3/scrutiny-web-linux-arm64"
		arm64.sha256 = "fb9da52142596ad0b7e9ded045aadda60a9de89ae1d490b126dcbc0347092f5c"

		autoupdate.strategy = "latest_github_release"
		autoupdate.asset.amd64 = "^scrutiny-web-linux-amd64$"
		autoupdate.asset.arm64 = "^scrutiny-web-linux-arm64$"

		[resources.sources.scrutiny-collector-metrics-linux]
		in_subdir = false
		rename = "scrutiny-collector-metrics-linux"
		amd64.url = "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.3/scrutiny-collector-metrics-linux-amd64"
		amd64.sha256 = "7be2294470a087083bab66c1fea8e1b4c278920b5c46ab80ed2c0cc8c4c0a2c3"
		arm64.url = "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.3/scrutiny-collector-metrics-linux-arm64"
		arm64.sha256 = "aa822526b601173a0951d6f75260f6a589d0d50731a8ae990223aa721e5f93c1"

		autoupdate.strategy = "latest_github_release"
		autoupdate.asset.amd64 = "^scrutiny-collector-metrics-linux-amd64$"
		autoupdate.asset.arm64 = "^scrutiny-collector-metrics-linux-arm64$"

		[resources.sources.scrutiny-web-frontend]
		in_subdir = true
		url = "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.3/scrutiny-web-frontend.tar.gz"
		sha256 = "3793f5a4f4f27f33527247243001b17399b0061e879322ca7f28e3d1b12f2686"

		autoupdate.strategy = "latest_github_release"
		autoupdate.asset = "^scrutiny-web-frontend.tar.gz$"

	[resources.system_user]

	[resources.install_dir]

	[resources.data_dir]

	[resources.permissions]
	main.url = "/"
	main.auth_header = false
	main.show_tile = true
	main.protected= true
	main.allowed = "admins"
	api.url = "re:__DOMAIN____PATH__/api/devices?/.*"
	api.allowed = "visitors"
	api.auth_header = false
	api.show_tile = false
	api.protected= true

	[resources.ports]
	main.default = 8080

	[resources.apt]
	packages = "smartmontools"
