#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "scrutiny-web-server" >/dev/null; then
	yunohost service remove "scrutiny-web-server"
fi
ynh_config_remove_systemd "scrutiny-web-server"

collector=$(ynh_app_setting_get --key=collector)
if [ $collector -eq 1 ]
then
	if ynh_hide_warnings yunohost service status "scrutiny-collector" >/dev/null
	then
		yunohost service remove "scrutiny-collector"
	fi
	ynh_config_remove_systemd "scrutiny-collector"
	ynh_safe_rm "/etc/systemd/system/scrutiny-collector.timer"
fi

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
