#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="influxdb" --action="stop"
ynh_systemctl --service="scrutiny-web-server.service" --action="stop" --log_path="/var/log/$app/web-server.log"
collector=$(ynh_app_setting_get --key=collector)
if [ $collector -eq 1 ]
then
	ynh_systemctl --service="scrutiny-collector.timer" --action="stop" --log_path="/var/log/$app/collector.log"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --source_id="scrutiny-web-linux" --dest_dir="$install_dir/bin"
ynh_setup_source --source_id="scrutiny-collector-metrics-linux" --dest_dir="$install_dir/bin"
ynh_setup_source --source_id="scrutiny-web-frontend" --dest_dir="$install_dir/web"

myynh_manage_influxdb2

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

if [ "${path}" == "/" ]
then
	base_path=""
else
	base_path="${path}"
fi
ynh_config_add --template="config/scrutiny.yaml" --destination="$install_dir/config/scrutiny.yaml"

		# Replace value in scrutiny.yaml
		ynh_replace --match="port: 8086" --replace="port: $influxdb_port" --file="$install_dir/config/scrutiny.yaml"
		ynh_replace --match="#token:" --replace="token:" --file="$install_dir/config/scrutiny.yaml"
		ynh_replace --match="#org:" --replace="org:" --file="$install_dir/config/scrutiny.yaml"
		ynh_replace --match="#bucket:" --replace="bucket:" --file="$install_dir/config/scrutiny.yaml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="scrutiny-web-server" --template="systemd-scrutiny-web-server.service"
yunohost service add "scrutiny-web-server" \
	--description="WebUI for smartd S.M.A.R.T monitoring" \
	--log="/var/log/$app/web-server.log" \
	--test_status="systemctl show scrutiny-web-server.service -p ActiveState --value | grep -v failed"

if [ $collector -eq 1 ]
then
	ynh_config_add --template="config/collector.yaml" --destination="$install_dir/config/collector.yaml"
	ynh_config_add --template="systemd-scrutiny-collector.service" --destination="/etc/systemd/system/scrutiny-collector.service"
	ynh_config_add --template="systemd-scrutiny-collector.timer" --destination="/etc/systemd/system/scrutiny-collector.timer"
	yunohost service add "scrutiny-collector" \
		--description="Collector running on timer (daily) for smartd S.M.A.R.T monitoring" \
		--log="/var/log/$app/collector.log" \
		--test_status="systemctl show scrutiny-collector.service -p ActiveState --value | grep -v failed"
fi

ynh_config_add_logrotate

myynh_set_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$influxdb_systemd_service_name" --action="enable"
ynh_systemctl --service="$influxdb_systemd_service_name" --action="restart"

ynh_systemctl --service="scrutiny-web-server.service" --action="enable"
ynh_systemctl --service="scrutiny-web-server.service" --action="start" --log_path="/var/log/$app/web-server.log"

if [ $collector -eq 1 ]
then
	ynh_systemctl --service="scrutiny-collector.timer" --action="enable"
	ynh_systemctl --service="scrutiny-collector.timer" --action="start" --log_path="/var/log/$app/collector.log"
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
